import "./ChatBox.css";
import { useState, type FormEvent } from "react";
import { useParams } from "react-router-dom";
import { getAuthHeaders } from "../../Auth/Auth";

type Message = {
  role: "user" | "assistant";
  content: string;
};

type ChatResponse = {
  message?: string;
};

function ChatBox() {
  const { creatureName } = useParams<{ creatureName: string }>();
  const [messages, setMessages] = useState<Message[]>([
    {
      role: "assistant",
      content: "Ask me anything about dinosaurs, periods, diets, or fossils.",
    },
  ]);
  const [input, setInput] = useState("");
  const [isSending, setIsSending] = useState(false);
  const API = import.meta.env.VITE_API_URL;

  const handleSend = async (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();

    const trimmedInput = input.trim();

    if (!trimmedInput || isSending) {
      return;
    }

    const nextMessages: Message[] = [
      ...messages,
      { role: "user", content: trimmedInput },
    ];

    setMessages(nextMessages);
    setInput("");
    setIsSending(true);

    try {
      const result = await fetch(`${API}/CreatureAIChat`, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          ...getAuthHeaders(),
        },
        body: JSON.stringify({
          creatureName: creatureName ?? "",
          messages: nextMessages,
        }),
      });

      if (!result.ok) {
        throw new Error("Chat request failed.");
      }

      const data: ChatResponse = await result.json();

      setMessages([
        ...nextMessages,
        {
          role: "assistant",
          content: data.message ?? "I could not generate a response.",
        },
      ]);
    } catch (error) {
      console.error("Error sending chat message:", error);
      setMessages([
        ...nextMessages,
        {
          role: "assistant",
          content: "Something went wrong. Try asking again in a moment.",
        },
      ]);
    } finally {
      setIsSending(false);
    }
  };

  return (
    <>
      <div className="chat-box">
        <div className="messages">
          {messages.map((msg, index) => (
            <div key={index} className={`message ${msg.role}`}>
              <strong>{msg.role === "user" ? "You" : "MesoDB AI"}</strong>
              <p>{msg.content}</p>
            </div>
          ))}
          {isSending ? (
            <div className="message assistant">
              <strong>MesoDB AI</strong>
              <p>Thinking...</p>
            </div>
          ) : (
            ""
          )}
        </div>
        <form className="input-area" onSubmit={handleSend}>
          <input
            type="text"
            value={input}
            onChange={(e) => setInput(e.target.value)}
            placeholder="Ask about a dinosaur..."
            disabled={isSending}
          />
          <button type="submit" disabled={isSending}>
            {isSending ? "Sending" : "Send"}
          </button>
        </form>
        <p id="ai_disc">
          These responses are generated by an AI and may not be accurate. Always
          double-check with trusted sources when researching dinosaurs.
        </p>
      </div>
    </>
  );
}

export default ChatBox;
